export default [
    "A cheetah can accelerate from 0 to 60 mph in just a few seconds.",
    "Lions are the only big cats that live in social groups called prides.",
    "Leopards can drag prey heavier than themselves into trees.",
    "Jaguars have the strongest bite force of all big cats.",
    "The black-footed cat has one of the highest hunting success rates among felines.",
    "Lynx have tufted ears that help enhance their hearing.",
    "Caracals can leap over 3 meters into the air to catch birds.",
    "Snow leopards use their long tails for balance in steep mountains.",
    "Fishing cats are excellent swimmers and actively hunt in water.",
    "A tiger’s roar can be heard from up to 3 kilometers away.",
    "Clouded leopards have some of the longest canine teeth relative to body size.",
    "Wild cats mark territory using scent glands and scratch marks.",
    "Cheetahs cannot roar — they communicate through chirps and purrs.",
    "Jaguars often hunt near rivers and wetlands.",
    "The serval has the longest legs relative to body size among wild cats.",
    "Sand cats can survive without drinking water for long periods.",
    "Lions spend up to 20 hours a day resting.",
    "Leopards are active mostly at night and are extremely stealthy.",
    "Lynx populations are slowly recovering in parts of Europe.",
    "Wild cats play a key role in keeping prey populations balanced.",
    "The ocelot’s spotted coat provides excellent camouflage in forests.",
    "Tigers are powerful swimmers and enjoy water.",
    "Caracals rely on explosive speed rather than endurance.",
    "Snow leopards cannot roar like lions or tigers.",
    "The fishing cat’s partially webbed paws help it hunt in wetlands.",
    "Jaguars can pierce turtle shells with their bite.",
    "Some wild cats can rotate their ears independently to detect sound.",
    "Habitat loss is the biggest threat to most wild feline species.",
    "A healthy predator population signals a healthy ecosystem.",
    "Protecting wild cats helps protect forests, grasslands, and wetlands too."
]